export const Locais = {
  "AGRO COORD": null,
  "ÁREAS COMUNS": null,
  "ARQUIVO MORTO": null,
  "ARTES RECEPÇÃO": null,
  "ARTES VISUAIS COORD": null,
  "ARTESANATO COORD": null,
  "AUDIOVIDEO COORD": null,
  "AUDIOVIDEO DEPÓSITO": null,
  B1T: null,
  "B5S CORREDOR": null,
  "B5T CORREDOR": null,
  B6S: null,
  "BACINE COORD": null,
  "BIBLIO ACERVO": null,
  "BIBLIO COORD": null,
  "BIBLIO COPA": null,
  "BIBLIO DML": null,
  "BIBLIO EST COLETIVO": null,
  "BIBLIO EST IND": null,
  "BIBLIO RECEPÇÃO": null,
  "BIBLIO SALA DE VIDEO": null,
  BIBLIOTECA: null,
  CAAAE: null,
  CAC: null,
  CAE: null,
  "CAE ATEN": null,
  "CAE ATENDIMENTO": null,
  "CAE RECEPÇÃO": null,
  "CAE ROL": null,
  CAM: null,
  CAP: null,
  "CAP DEPÓSITO": null,
  CG: null,
  CGOF: null,
  "CHEFIA DE GABINETE": null,
  CINEMA: null,
  COMUNICAÇÃO: null,
  "COORD. EDIFICAÇÕES": null,
  "COORD/PROCESSAMENTO": null,
  "Coordenação ACADEMICA": null,
  "COPA B1": null,
  COPINHA: null,
  "COPINHA B1": null,
  CORAE: null,
  "COZINHA RESTAURANTE": null,
  DAA: null,
  "DAA ROL": null,
  "Depósito do Almox e Patr.": null,
  DG: null,
  "DIREÇÃO GERAL": null,
  "DML B1": null,
  ESTÁGIO: null,
  GA: null,
  GEPEX: null,
  "GEPEX 2": null,
  "LAB INFO": null,
  "Lab Instalações Prediais": null,
  "LABORATÓRIO BIOLOGIA": null,
  "LABORATÓRIO CIÊNCIAS": null,
  "LABORATÓRIO DE BIOLOGIA": null,
  "Localização (Entidade que está responsável ou utilizando)": null,
  NPD: null,
  "NUCLEO DE PESQUISA": null,
  "PONTO ELETRÔNICO": null,
  RECEPÇÃO: null,
  "RECEPÇÃO B1": null,
  RESTAURANTE: null,
  RH: null,
  "ROL 1 B1": null,
  "ROL 2 B1": null,
  S501: null,
  S502: null,
  S503: null,
  S504: null,
  S505: null,
  S506: null,
  "S601 Lab. infomática ": null,
  S602: null,
  S603: null,
  "S603 (NPD)": null,
  S604: null,
  S606: null,
  S609: null,
  "SALA DE PROJEÇÃO": null,
  "SALA DE REUNIÕES": null,
  "Sala de TI": null,
  "SALA DO SERVIDOR": null,
  "SALA DOS PROFESSORES": null,
  "Sala dos Professores": null,
  "SALA DOS PROFESSORES COPA": null,
  "SALA GRANDE": null,
  "SALA INFORMÁTICA": null,
  "SALA TECNICOS CIÊNCIAS": null,
  "SALA TECNICOS EDIFICAÇÕES": null,
  "SALA TECNICOS LABINFO": null,
  "SALÃO DE EVENTOS": null,
  "SALÃO DE EVENTOS DEPÓSITO": null,
  "SALÃO DE EVENTOS DML": null,
  T501: null,
  T502: null,
  T503: null,
  T504: null,
  T505: null,
  T506: null,
  T601: null,
  T602: null,
  T605: null,
  T606: null,
  T607: null,
  T608: null,
  T609: null,
  T610: null,
  "TERCEIRIZADOS ALMOXARIFADO": null,
  "TERCEIRIZADOS COPA": null,
  TI: null,
  "TI CPD": null,
  "TI OFICINA": null,
  "TI SALA PROF": null,
  "TI SERVIDOR": null,
  "TI ST B1T": null,
  "TI ST B2T": null,
  "TI ST B5S": null,
  "TI ST B5T": null,
  "TI ST B6S": null,
  "TI ST B6T": null,
  "TI ST BIBLIO": null,
  "TI ST S602": null,
};

export const Status = {
  BOM: null,
  DANIFICADO: null,
  IRRECUPERAVEL: null,
  ANTIECONÔMICO: null,
};

export const responsavel = {
  "abishai.neto@ifg.edu.br": null,
  "aderito.tavora@ifg.edu.br": null,
  "adria.cerqueira@ifg.edu.br": null,
  "alemar.sousa@ifg.edu.br": null,
  "ana.carolina@ifg.edu.br": null,
  "ana.freire@ifg.edu.br": null,
  "ana.jardim@ifg.edu.br": null,
  "ana.magalhaes@ifg.edu.br": null,
  "ana.silva@ifg.edu.br": null,
  "antonio.barbosa@ifg.edu.br": null,
  "carlos.cipriano@ifg.edu.br": null,
  "carlos.neto@ifg.edu.br": null,
  "cibele.araujo@ifg.edu.br": null,
  "ciro.macedo@ifg.edu.br": null,
  "claudia.trindade@ifg.edu.br": null,
  "cristiane.alves@ifg.edu.br": null,
  "cristiane.ventura@ifg.edu.br": null,
  "cristiano.jose@ifg.edu.br": null,
  "danilo.nascimento@ifg.edu.br": null,
  "deryk.santana@ifg.edu.br": null,
  "diego.ferreira@ifg.edu.br": null,
  "diogo.pinto@ifg.edu.br": null,
  "eduardo.bittencourt@ifg.edu.br": null,
  "elder.queiroz@ifg.edu.br": null,
  "eliana.silva@ifg.edu.br": null,
  "emicleia.pinheiro@ifg.edu.br": null,
  "erica.zanon@ifg.edu.br": null,
  "erick.silva@ifg.edu.br": null,
  "estevao.garcia@ifg.edu.br": null,
  "euzamar.oliveira@ifg.edu.br": null,
  "fabiana.andersson@ifg.edu.br": null,
  "fabiana.macedo@ifg.edu.br": null,
  "fabricio.silva@ifg.edu.br": null,
  "fernando.moreno@ifg.edu.br": null,
  "fernando.bastos@ifg.edu.br": null,
  "flavia.schmidt@ifg.edu.br": null,
  "flora.ruiz@ifg.edu.br": null,
  "gabriela.borges@ifg.edu.br": null,
  "gabriel.madeira@ifg.edu.br": null,
  "guilherme.martins@ifg.edu.br": null,
  "haroldo.filho@ifg.edu.br": null,
  "Iara.pina@ifg.edu.br": null,
  "isaias.neto@ifg.edu.br": null,
  "jansen.ramos@ifg.edu.br": null,
  "jeff.jno@ifg.edu.br": null,
  "jose.nerivaldo@ifg.edu.br": null,
  "kamilla.palhares@ifg.edu.br": null,
  "kelly.silva@ifg.edu.br": null,
  "lais.almeida@ifg.edu.br": null,
  "larissa.miziara@ifg.edu.br": null,
  "leandro.neto@ifg.edu.br": null,
  "lorena.moraes@ifg.edu.br": null,
  "lucas.andrade@ifg.edu.br": null,
  "luciana.ribeiro@ifg.edu.br": null,
  "luciane.borges@ifg.edu.br": null,
  "luzia.guasco@ifg.edu.br": null,
  "maloni.mafei@ifg.edu.br": null,
  "marco.queiroz@ifg.edu.br": null,
  "meire.goncalves@ifg.edu.br": null,
  "michelly.santos@ifg.edu.br": null,
  "nadia.pinheiro@ifg.edu.br": null,
  "naira.silva@ifg.edu.br": null,
  "patricia.tavares@ifg.edu.br": null,
  "paula.lima@ifg.edu.br": null,
  "paulo.freitas@ifg.edu.br": null,
  "paulo.nunes@ifg.edu.br": null,
  "rafael.carmo@ifg.edu.br": null,
  "rafael.resende@ifg.edu.br": null,
  "raquel.cruz@ifg.edu.br": null,
  "regina.melo@ifg.edu.br": null,
  "renata.brito@ifg.edu.br": null,
  "renato.prado@ifg.edu.br": null,
  "renne.franca@ifg.edu.br": null,
  "rita.holdefer@ifg.edu.br": null,
  "romulo.azevedo@ifg.edu.br": null,
  "rosirene.santos@ifg.edu.br": null,
  "ruslana.alves@ifg.edu.br": null,
  "samuel.rodrigues@ifg.edu.br": null,
  "sandro.di.lima@ifg.edu.br": null,
  "stenio.oliveira@ifg.edu.br": null,
  "suzane.milhomem@ifg.edu.br": null,
  "thaisa.nascimento@ifg.edu.br": null,
  "thiago.faria@ifg.edu.br": null,
  "thiago.nascimento@ifg.edu.br": null,
  "tiago.garcia@ifg.edu.br": null,
  "ubirajara.castro@ifg.edu.br": null,
  "victor.cruzeiro@ifg.edu.br": null,
  "wagner.carlos@ifg.edu.br": null,
  "welington.passarinho@ifg.edu.br": null,
};
